# CREATED USING EXTERNAL TWEAKER

mods.immersiveengineering.Blueprint.removeRecipe(<immersiveengineering:material:27>);
mods.immersiveengineering.Blueprint.removeRecipe(<immersiveengineering:material:26>);
mods.immersiveengineering.Blueprint.addRecipe("components", <immersiveengineering:material:26> * 4, [<immersiveengineering:material:20> * 4, <immersiveengineering:material:8> * 2, <minecraft:redstone> * 2, <ore:plateNickel> * 2]);
mods.immersiveengineering.Blueprint.addRecipe("components", <powersuits:powerarmorcomponent:5> * 2, [<minecraft:clay_ball> * 4, <powersuits:powerarmorcomponent> * 2, <ore:plateTin> * 2, <techreborn:rebattery> * 2]);
mods.immersiveengineering.Blueprint.addRecipe("components", <powersuits:powerarmorcomponent:6> * 2, [<powersuits:powerarmorcomponent:5>, <powersuits:powerarmorcomponent> * 4, <techreborn:energycrystal> * 2, <ore:ingotNiobium> * 4, <powersuits:powerarmorcomponent:21> * 4, <techreborn:part:35> * 8]);
mods.immersiveengineering.Blueprint.addRecipe("components", <powersuits:powerarmorcomponent:7> * 2, [<powersuits:powerarmorcomponent:6>, <powersuits:powerarmorcomponent> * 8, <techreborn:lapotroncrystal> * 2, <techreborn:plates:20> * 6, <techreborn:part:42> * 2, <techreborn:part:35> * 6]);
mods.immersiveengineering.Blueprint.addRecipe("components", <powersuits:powerarmorcomponent:8> * 2, [<powersuits:powerarmorcomponent:7> * 2, <powersuits:powerarmorcomponent:20>, <techreborn:plates:2> * 6, <ore:gemSapphire> * 2]);
mods.immersiveengineering.Blueprint.addRecipe("components", <techreborn:part:29>, [<techreborn:part:40>, <minecraft:redstone> * 8, <techreborn:cable:5> * 16, <ore:plateIron> * 2, <powersuits:powerarmorcomponent:5> * 2, <techreborn:part:32> * 4]);
mods.immersiveengineering.Blueprint.addRecipe("GonerMachine", <powersuits:powerarmor_head>.withTag({MMModItem: {commonValues: {}}}), [<techreborn:plates:38> * 16, <techreborn:reinforced_glass> * 2, <powersuits:powerarmorcomponent:15> * 8, <immersiveengineering:material:9> * 10]);
mods.immersiveengineering.Blueprint.addRecipe("GonerMachine", <powersuits:powerarmor_torso>.withTag({MMModItem: {commonValues: {}}}), [<techreborn:plates:38> * 32, <powersuits:powerarmorcomponent:15> * 10, <immersiveengineering:material:9> * 16]);
mods.immersiveengineering.Blueprint.addRecipe("GonerMachine", <powersuits:powerarmor_legs>.withTag({MMModItem: {commonValues: {}}}), [<techreborn:plates:38> * 24, <powersuits:powerarmorcomponent:15> * 12, <immersiveengineering:material:9> * 24]);
mods.immersiveengineering.Blueprint.addRecipe("GonerMachine", <powersuits:powerarmor_feet>.withTag({MMModItem: {commonValues: {}}}), [<techreborn:plates:38> * 12, <powersuits:powerarmorcomponent:15> * 8, <immersiveengineering:material:9> * 20]);
mods.immersiveengineering.Blueprint.addRecipe("GonerMachine", <powersuits:power_fist>.withTag({MMModItem: {commonValues: {}}}), [<techreborn:plates:38> * 8, <powersuits:powerarmorcomponent:15> * 32, <immersiveengineering:material:9> * 32]);
mods.immersiveengineering.Blueprint.addRecipe("components", <techreborn:part:42> * 2, [<embers:shard_ember> * 2, <techreborn:part:40> * 2, <minecraft:redstone_block>, <techreborn:cable:2> * 16]);
mods.immersiveengineering.Blueprint.addRecipe("generator", <techreborn:gas_turbine>, [<ore:plateAluminium> * 8, <techreborn:part:30> * 4, <mist:niobium_ore> * 4, <techreborn:reinforced_glass> * 2, <immersiveengineering:metal_device1:2> * 2, <immersiveengineering:material:9> * 4, <techreborn:machine_casing:1>, <powersuits:powerarmorcomponent> * 16]);
mods.immersiveengineering.Blueprint.addRecipe("generator", <techreborn:plasma_generator>, [<techreborn:plates:33> * 8, <techreborn:hv_transformer>, <techreborn:part> * 4, <immersiveengineering:metal_decoration0:2> * 4, <immersiveengineering:metal_device1:3> * 2, <powersuits:powerarmorcomponent> * 16]);
mods.immersiveengineering.Blueprint.addRecipe("generator", <techreborn:semi_fluid_generator>, [<embers:combustor>, <techreborn:part:29> * 4, <mist:niobium_ore> * 8, <techreborn:reinforced_glass> * 4, <techreborn:lithiumbattery> * 2, <techreborn:plates:35> * 6, <immersiveengineering:material:9> * 8, <powersuits:powerarmorcomponent> * 16]);
mods.immersiveengineering.Blueprint.addRecipe("generator", <immersiveengineering:metal_device1:2>, [<ore:plateSteel> * 6, <immersiveengineering:metal_decoration0> * 2, <immersiveengineering:material:1> * 5, <immersiveengineering:material:8> * 6, <techreborn:rebattery>, <ore:itemRubber> * 6]);
mods.immersiveengineering.DieselHandler.addFuel(<liquid:fluidnitrodiesel>, 4000);
mods.immersiveengineering.DieselHandler.addFuel(<liquid:fluidnitrofuel>, 3000);
mods.immersiveengineering.DieselHandler.addFuel(<liquid:fluidnitrocoalfuel>, 2500);
mods.immersiveengineering.Excavator.addMineral("Niobium ", 30, 0.005, ["oreBioshar", "oreNiobium", "oreBone"], [60, 30, 20], [69]);
mods.immersiveengineering.Excavator.addMineral("�ٿ���", 10, 0.05, ["oreTungsten", "oreSheldonite", "oreIron", "oreSphalerite"], [60, 10, 20, 10], [0]);
mods.immersiveengineering.Excavator.addMineral("Acientwood", 10, 0.09, ["oreSand", "oreAcientwood", "oreAmber"], [55, 45, 5]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <techreborn:solar_panel>, [<techreborn:machine_frame>, <ore:paneGlass> * 8, <techreborn:part:29> * 2, <ore:dustCharcoal> * 8, <powersuits:powerarmorcomponent> * 16, <immersiveengineering:material:8> * 8, <techreborn:plates:11> * 6, <embers:shard_ember> * 4]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <techreborn:solar_panel:1>, [<techreborn:solar_panel> * 8, <techreborn:lv_transformer>, <techreborn:part:29> * 2, <techreborn:plates:2> * 8, <powersuits:powerarmorcomponent> * 16, <immersiveengineering:material:8> * 8]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <techreborn:solar_panel:2>, [<techreborn:solar_panel:1> * 8, <techreborn:mv_transformer>, <techreborn:part:30> * 2, <techreborn:machine_casing:1>, <powersuits:powerarmorcomponent> * 16, <mist:niobium_ingot> * 8]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <techreborn:solar_panel:3>, [<techreborn:solar_panel:2> * 8, <techreborn:hv_transformer>, <techreborn:part> * 2, <techreborn:machine_casing:1>, <powersuits:powerarmorcomponent> * 16, <techreborn:plates:20> * 8]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <techreborn:solar_panel:4>, [<techreborn:solar_panel:3> * 4, <techreborn:ev_transformer>, <powersuits:powerarmorcomponent:8> * 4, <techreborn:machine_casing:2>, <powersuits:powerarmorcomponent:15> * 2, <techreborn:plates:38> * 4, <techreborn:reinforced_glass> * 8, <techreborn:cable:8> * 2]);
mods.immersiveengineering.Blueprint.addRecipe("SolarPannel", <powersuits:powerarmorcomponent:18>, [<techreborn:solar_panel:3>, <techreborn:reinforced_glass> * 6, <powersuits:powerarmorcomponent:15>, <techreborn:plates:24> * 4]);
mods.immersiveengineering.ArcFurnace.addRecipe(<techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidsilicon", Amount: 1000}}), <ore:sand>, <immersiveengineering:material:7>, 1600, 2048, [<minecraft:coal> * 3]);
mods.immersiveengineering.MetalPress.addRecipe(<techreborn:plates:11>, <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "fluidsilicon", Amount: 1000}}), <immersiveengineering:mold>, 2000, 1);
mods.immersiveengineering.ArcFurnace.addRecipe(<techreborn:ingot:19>, <techreborn:dust:32>, <immersiveengineering:material:7>, 800, 2048, [<ore:oreIron> * 6]);
//���Ӵ���ʯ��ĩ�䷽
mods.immersiveengineering.Crusher.addRecipe(<techreborn:dust:32>, <ore:stoneMarble> * 2, 1024, <taiga:valyrium_dust>, 0.003);
